<!DOCTYPE html>
<html lang="<?php echo $this->config->application->language;?>">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="description" content="<?php echo $this->config->application->description;?>" />
    <meta name="author" content="manafx.com" />
    <link rel="shortcut icon" href="<?php echo $this->config->application->baseUrl . "/favicon.ico";?>" />

    <title><?php echo $this->config->application->title;?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $templateUri . '/themes/' . $current_theme . '/bootstrap.min.css';?>" />
    <?php
			$this->assets->addCss($templateUri . '/themes/' . $current_theme . '/style.css');
			$this->assets->outputCss();
    ?>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <?php
    	/*
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      */
			$this->assets
			    ->collection('ie-support')
			    ->addJs($templateUri . '/js/html5shiv.js')
			    ->addJs($templateUri . '/js/respond.min.js');
			$this->assets->outputJs('ie-support');
    ?>
    <![endif]-->
    <?php
			$this->assets
			    ->collection('header-static')
			    ->addJs($templateUri . '/js/jquery-1.11.0.min.js');
		?>
    <?php $this->assets->outputJs('header-static'); ?>
    <?php $this->assets->outputJs('header-dynamic'); ?>
    <?php echo $headerfooter->get_header();?>
	</head>
	<body>
		<div id="wrapper-main">
			<?php  include("navbar-frontend.phtml"); ?>
	    <div id="wrapper-content" class="container-fluid <?php echo $module_name . ' ' . $module_name.'-'.$controller_name . ' ' . $module_name.'-'.$controller_name.'-'.$action_name;?>">
	      <div class="row">
					<?php echo $this->getContent();?>
				</div>
			</div>
			<div id="wrapper-footer" class="container-fluid <?php echo $module_name.'-'.$controller_name.'-'.$action_name;?>">

				<footer role="contentinfo" class="footer">
					<div class="row">
						<div id="social-platforms">
						  <a class="btn-social btn-icon btn-facebook" href="#"><i class="fa fa-facebook"></i><span>Facebook</span></a>
						  <a class="btn-social btn-icon btn-twitter" href="https://twitter.com/mannacode"><i class="fa fa-twitter"></i><span>Twitter</span></a>
						  <a class="btn-social btn-icon btn-googleplus" href="#"><i class="fa fa-google-plus"></i><span>Google+</span></a>
						  <a class="btn-social btn-icon btn-pinterest" href="#"><i class="fa fa-pinterest"></i><span>Pinterest</span></a>
						  <a class="btn-social btn-icon btn-linkedin" href="#"><i class="fa fa-linkedin"></i><span>LinkedIn</span></a>
						  <a class="btn-social btn-icon btn-github" href="https://github.com/manacode/manafx"><i class="fa fa-github"></i><span>GitHub</span></a>
						</div>

						<p>Coded and built with all of the good hopes by <a target="_blank" href="https://twitter.com/mannacode">@mannacode</a>.</p>
						<p>Code licensed <a target="_blank" href="https://github.com/manacode/manafx/blob/master/LICENSE" rel="license">MIT</a>, docs <a target="_blank" href="https://creativecommons.org/licenses/by/3.0/" rel="license">CC BY 3.0</a>.</p>
					</div>
				</footer>
			</div>
		</div>
		<?php # echo $getOffline;?>
		<?php
			$this->assets
			    ->collection('footer-static')
			    ->addJs($templateUri . '/js/bootstrap.min.js');
			    
			// $this->assets->collection('footer-dynamic');
			$this->assets->outputJs('footer-static');
			$this->assets->outputJs('footer-dynamic');

		?>
		
  </body>
</html>