<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="description" content="<?php echo $this->config->application->description;?>" />
    <meta name="author" content="manafx.com" />
    <link rel="shortcut icon" href="<?php echo $this->config->application->baseUrl . "/favicon.ico";?>" />

    <title><?php echo $this->config->application->title;?></title>
    <?php
			$this->assets->addCss($templateUri . '/themes/' . $current_theme . '/bootstrap.min.css');
			$this->assets->addCss($templateUri . '/themes/' . $current_theme . '/backend.css');
			$this->assets->outputCss();
    ?>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <?php
			$this->assets
			    ->collection('header-static')
			    ->addJs($templateUri . '/js/html5shiv.js')
			    ->addJs($templateUri . '/js/respond.min.js');
    ?>
    <![endif]-->
    <?php
			$this->assets
			    ->collection('header-static')
			    ->addJs($templateUri . '/js/jquery-1.11.0.min.js')
			    ->addJs($templateUri . '/js/jquery.cookie.js?v=1.4.1');
		?>
    <?php $this->assets->outputJs('header-static'); ?>
    <?php $this->assets->outputJs('header-dynamic'); ?>
    <?php echo $headerfooter->get_header();?>
	</head>
	<body>
		<div id="wrapper-main" class="session">
			<?php include("navbar-backend.phtml"); ?>
	    <div id="wrapper-content" class="container-fluid <?php echo $module_name . ' ' . $module_name.'-'.$controller_name . ' ' . $module_name.'-'.$controller_name.'-'.$action_name;?>">
	      <div class="row">
					<?php echo $this->getContent();?>
				</div>
				<div class="clearfix">&nbsp;</div>
			</div>
			<div id="wrapper-footer" class="session <?php echo $module_name.'-'.$controller_name.'-'.$action_name;?>">
				<p class="small">Application &amp; Content Management System<br />
					&copy; 2012 - <?php echo $this->dt->mdate("Y");?> <a href="http://manafx.com">ManaFx</a>, All Rights Reserved. Powered by <a href="http://manafx.com">Mana Application Framework</a>.
				</p>
			</div>
		</div>
		<?php
			$this->assets
			    ->collection('footer-static')
			    ->addJs($templateUri . '/js/bootstrap.min.js')
			    ->addJs($templateUri . '/js/manafx.js');
			    
			$this->assets->outputJs('footer-static');
			$this->assets->outputJs('footer-dynamic');
		?>
  </body>
</html>