<?php
	$headerfooter->add_css(array(
		array(
			"path" => $templateUri . "/css/image-hover-ie7.css",
			"priority" => 0,
			"condition" => "IE 7"
		),
		array(
			"path" => $templateUri . "/css/image-hover-ie8.css",
			"priority" => 0,
			"condition" => "IE 8"
		),
	));
	$this->assets->addCss($templateUri . "/css/flags.css");
	$this->assets->addCss($templateUri . "/common/bootstrap-select/css/bootstrap-select.min.css");
	$this->assets
	    ->collection('header-dynamic')
	    ->addJs($templateUri . "/common/bootstrap-select/js/bootstrap-select.min.js");
?>
<div class="col-sm-12 col-md-12">
  <h2 class="page-header"><span class="glyphicon glyphicon-globe"></span> <?php echo $this->t->_("Languages");?></h2>
  <?php $this->flashSession->output(); ?>
  <?php if ($this->auth->edit) { ?>
	<h3><?php echo $this->t->_("Edit Language Info");?></h3>
  <form method="post" action="<?php echo $adminurl . "/languages/edit";?>">
    <input type="hidden" name="update" value="update" />
	  <div class="col-xs-12 col-sm-4 col-md-3">
		  <div class="row">
			  <div class="form-group">
			    <label for="languageCode"><?php echo $this->t->_("Language Code");?></label>
			    <input type="hidden" id="languageCode" name="languageInfo[code]" value="<?php echo $languageInfo['code'];?>" />
		    	<p class="form-control btn-default active"><?php echo $languageInfo['code'];?></p>
			  </div>
	    </div>
		  <div class="row">
			  <div class="form-group">
			    <label for="languageName"><?php echo $this->t->_("Language Name");?></label>
		    	<input type="text" class="form-control" id="languageName" name="languageInfo[name]" value="<?php echo $languageInfo['name'];?>" />
			  </div>
	    </div>
		  <div class="row">
			  <div class="form-group">
			  	<label><?php echo $this->t->_("Language Direction");?></label>
			  	<div class="form-control">
						<label class="radio-inline">
						  <input type="radio" name="languageInfo[rtl]" id="directionLTR" value="0" <?php echo ($languageInfo['rtl']=="0") ? 'checked="checked"' : '' ;?> /> LTR
						</label>
						<label class="radio-inline">
						  <input type="radio" name="languageInfo[rtl]" id="directionRTL" value="1" <?php echo ($languageInfo['rtl']=="1") ? 'checked="checked"' : '' ;?> /> RTL
						</label>
					</div>
		  	</div>
	    </div>
		  <div class="row">
			  <div class="form-group">
			    <label for="languageVersion"><?php echo $this->t->_("Version");?></label>
		    	<input type="text" class="form-control" id="languageVersion" name="languageInfo[version]" value="<?php echo $languageInfo['version'];?>" />
			  </div>
	    </div>
		  <div class="row">
			  <div class="form-group">
			    <label for="languageVersion"><?php echo $this->t->_("Creation Date");?></label>
		    	<input type="text" class="form-control" id="languageCreationDate" name="languageInfo[creation_date]" value="<?php echo $languageInfo['creation_date'];?>" />
			  </div>
	    </div>
		  <div class="row">
			  <div class="form-group">
			    <label for="languageAuthor"><?php echo $this->t->_("Author");?></label>
		    	<input type="text" class="form-control" id="languageAuthor" name="languageInfo[author]" value="<?php echo $languageInfo['author'];?>" />
			  </div>
	    </div>
  	</div>
	  <div class="col-xs-12 col-sm-7 col-sm-offset-1 col-md-8 col-md-offset-1">
		  <div class="row">
			  <div class="form-group">
			    <label for="languageAuthorUri"><?php echo $this->t->_("Author Uri");?></label>
		    	<input type="text" class="form-control" id="languageAuthorUri" name="languageInfo[author_uri]" value="<?php echo $languageInfo['author_uri'];?>" />
			  </div>
	    </div>
		  <div class="row">
			  <div class="form-group">
			    <label for="languageDescription"><?php echo $this->t->_("Description");?></label>
		    	<input type="text" class="form-control" id="languageDescription" name="languageInfo[description]" value="<?php echo $languageInfo['description'];?>" />
			  </div>
	    </div>
		  <div class="row">
			  <div class="form-group">
			    <label for="languageLocale"><?php echo $this->t->_("Locale");?></label>
		    	<input type="text" class="form-control" id="languageLocale" name="languageInfo[locale]" value="<?php echo $languageInfo['locale'];?>" />
			  </div>
	    </div>
		  <div class="row">
			  <div class="form-group">
			    <label for="languageLicense"><?php echo $this->t->_("License");?></label>
		    	<input type="text" class="form-control" id="languageLicense" name="languageInfo[license]" value="<?php echo $languageInfo['license'];?>" />
			  </div>
	    </div>
		  <div class="row">
			  <div class="form-group">
			    <label for="languageLicenseUri"><?php echo $this->t->_("License Uri");?></label>
		    	<input type="text" class="form-control" id="languageLicenseUri" name="languageInfo[license_uri]" value="<?php echo $languageInfo['license_uri'];?>" />
			  </div>
	    </div>
		  <div class="row">
		    <button id="btnSubmit" class="btn btn-primary" type="button"><?php echo $this->t->_("Update");?></button>
	    </div>
    </div>
	</form>
	<?php }?>
</div>