<?php
	$this->assets->addCss($templateUri . "/css/flags.css");
	$this->assets->addCss($templateUri . "/common/bootstrap-select/css/bootstrap-select.min.css");
	$this->assets->addCss($templateUri . "/common/footable/css/footable.core.min.css");
	$this->assets
	    ->collection('header-dynamic')
	    ->addJs($templateUri . "/common/footable/js/footable.all.min.js");
?>
<div class="col-sm-12 col-md-12">
  <h2 class="page-header"><span class="glyphicon glyphicon-globe"></span> <?php echo $this->t->_("Edit Translation");?></h2>
  <?php $this->flashSession->output(); ?>
	<?php
		$flang = strtolower($languageCode);
		if (strlen($flang)>2) {
			$flang = substr($flang, -2);
		}
	?>
	<div class="container-fluid">
		<div class="row">
			<button class="btn btn-dark margin-please" type="button" data-toggle="collapse" data-target="#LanguageInfo" aria-expanded="false" aria-controls="LanguageInfo">
				<span class="glyphicon flag flag-<?php echo $flang;?>"> &nbsp;</span> <?php echo $languageFileName;?>
			</button>
			<div class="collapse" id="LanguageInfo">
			  <div class="well well-small">
				  <ul class="list-unstyled">
				    <li class="text-info"><strong><?php echo $this->t->_("Language");?>: </strong><span class="list-group-item-text"><?php echo $languageCode;?></span></li>
				    <li class="text-info"><strong><?php echo $this->t->_("Module");?>: </strong><span class="list-group-item-text"><?php echo $languageModule;?></span></li>
			  	</ul>
			  </div>
			</div>
		  <div class="pull-right">
				<button id="btnUpdateTranslation" class="btn btn-default margin-please" type="button" disabled="disabled">
					<span class="glyphicon glyphicon-save-file" aria-hidden="true"></span> <?php echo $this->t->_("Update Translation");?>
				</button>
				<button class="btnBack btn btn-default margin-please" type="submit">
					<span class="glyphicon glyphicon-arrow-left"></span> <?php echo $this->t->_("back_manage_language", "Back");?>
				</button>
				<form role="form" method="post" id="frmBack" action="<?php echo $adminurl . "/languages/manage";?>">
					<input type="hidden" name="languageCode" value="<?php echo $languageCode;?>" />
				</form>
			</div>
		</div>
	</div>
	<div class="clearfix">&nbsp;</div>
	<?php echo $this->gridToolbar->output(); ?>
	<div class="table-responsive datagrid">
		<form role="form" method="post" id="frmTranslation" action="<?php echo $adminurl . "/languages/updateTranslation";?>">
			<input type="hidden" name="languageCode" value="<?php echo $languageCode;?>" />
			<input type="hidden" name="languageFileName" value="<?php echo $languageFileName;?>" />
			<input type="hidden" name="languageFilePath" value="<?php echo $languageFilePath;?>" />
			<table class="table footable table-hover table-condensed" data-page-size="<?php echo $this->config->public->grid_rows;?>" data-limit-navigation="5" data-filter="#search-filter">
				<thead>
				  <tr>
	          <th data-sort-ignore="true" class="col4checkbox"><input id="check-all" type="checkbox" /></th>
			      <th data-toggle="true">Translation Key</th>
			      <th data-hide="phone">Translation Value</th>
			      <?php if ($this->auth->edit) { ?><th data-sort-ignore="true" class="column-icon"></th><?php }?>
			      <?php if ($this->auth->delete) { ?><th data-sort-ignore="true" class="column-icon"></th><?php }?>
				  </tr>
				</thead>
				<tbody>
				<?php foreach($languageFileContent as $key => $val) { ?>
						<tr data-id="<?php echo $key;?>">
							<td class="col4checkbox"><input class="check-rows" name="checked_id[]" type="checkbox" value="<?php echo $key;?>" /></td>
							<td><input type="hidden" name="translationKey[]" value="<?php echo $key;?>" /><span class="translationKey"><?php echo $key;?></span></td>
							<td><input type="hidden" name="translationValue[]" value="<?php echo $val;?>" /><span><?php echo $val;?></span></td>
							<?php if ($this->auth->edit) { ?><td><button class="btnEdit btn btn-primary btn-xs" title="Edit `<?php echo $key;?>`"><span class="glyphicon glyphicon-edit"></span></button></td><?php }?>
							<?php if ($this->auth->delete) { ?><td><button class="btnDelete btn btn-danger btn-xs" title="Delete `<?php echo $key;?>`"><span class="glyphicon glyphicon-remove"></span></button></td><?php }?>
						</tr>
				<?php } ?>
				</tbody>
				<tfoot class="hide-if-no-paging">
					<tr>
						<td colspan="6">
							<div class="text-center">
								<ul class="pagination pagination-centered"></ul>
							</div>
						</td>
					</tr>
				</tfoot>
			</table>
		</form>
	</div>
</div>

<div id="editTranslation" class="add-edit-modal modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel" text-create="<?php echo $this->t->_("add_translation", "Add Translation");?>" text-edit="<?php echo $this->t->_("edit_translation", "Edit Translation");?>">Add Translation</h4>
      </div>
      <div class="modal-body">
				<form role="form">
					<input type="hidden" id="purpose" value="" />
				  <div class="form-group">
				    <label for="translationKey">Translation Key</label>
				    <input type="text" class="form-control" id="translationKey" />
				  </div>
				  <div class="form-group">
				    <label for="translationValue">Translation Value</label>
				    <textarea class="form-control" id="translationValue" rows="3"></textarea>
				  </div>
				</form>
				<div id="addeditMsg" class="alert alert-success hide"></div>
      </div>
      <div class="modal-footer">
        <button type="button" id="btnUpdateForm" class="btn btn-primary"><?php echo $this->t->_("Update Form");?></button>
        <button type="button" id="btnClose" class="btn btn-default" data-dismiss="modal"><?php echo $this->t->_("Close");?></button>
      </div>
    </div>
  </div>
</div>

<div id="deleteTranslation" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 id="myModalLabel"><?php echo $this->t->_("Delete Translation Confirmation");?></h4>
			</div>
			<div class="modal-body">
			  <form name="frmDelete">
			  	<input type="hidden" id="translationKey" />
				</form>
				<p id="confirmDeleteMany" class="hidden"><?php echo $this->t->_("delete_translation_keys", "Are you sure you want to delete selected translation keys?");?> <br /> <span id="keys2delete"></span></p>
				<p id="confirmDeleteOne" class="hidden"><?php echo $this->t->_("delete_translation_key", "Are you sure you want to delete translation key");?>: <strong id="key2delete"></strong>?</p>
			</div>
			<div id="deleteMsg" class="alert alert-danger hide"></div>
			<div class="modal-footer">
				<button type="button" id="btnDeleteNow" class="btn btn-primary" class="btn btn-primary"><?php echo $this->t->_("Delete");?></button>
				<button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true"><?php echo $this->t->_("Cancel");?></button>
			</div>
		</div>
	</div>
</div>