<div class="col-sm-12 col-md-12">
  <h2 class="page-header"><span class="glyphicon glyphicon-asterisk"></span> Change Password</h2>
  <?php $this->flashSession->output();?>

	<div class="col-sm-9 col-md-9">
  	<form role="form" class="form form-horizontal" method="post" autocomplete="off">

		
			<div class="form-group">
				<label for="old_password" class="col-sm-3 control-label">Current Password</label>
				<div class="col-sm-6">
					<?php echo $form->render("old_password") ?>
				</div>
			</div>

			<div class="form-group">
				<label for="user_password" class="col-sm-3 control-label">New Password</label>
				<div class="col-sm-6">
					<?php echo $form->render("user_password") ?>
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-sm-3 control-label"></label>
				<div class="col-sm-6">
					<div class="progress">
					  <div id="pwstrength" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
					  </div>
					</div>
		    </div>
			</div>
		
			<div id="confirmation" class="form-group">
				<label for="confirm_pass" class="col-sm-3 control-label">Confirm Password</label>
				<div class="col-sm-6">
					<?php echo $form->render("confirm_pass") ?>
					<span class="glyphicon form-control-feedback"></span>
				</div>
			</div>
			
			<div class="form-group">
				<div class="col-sm-offset-3 col-sm-6">
					<input type="submit" value="Save Changes" class="btn btn-primary" />
				</div>
			</div>
		
		</form>
	</div>
