<?php
	$this->assets->addCss($templateUri . "/common/footable/css/footable.core.min.css");
	$this->assets
	    ->collection('header-dynamic')
	    ->addJs($templateUri . "/common/footable/js/footable.all.min.js");
?>

<div class="col-sm-12 col-md-12">
  <h2 class="page-header"><span class="glyphicon glyphicon-cog"></span> Options</h2>
  <?php $this->flashSession->output(); ?>
  <?php echo $this->gridToolbar->output(); ?>
	<div class="table-responsive datagrid">
		<table class="table footable table-hover table-condensed" data-page-size="<?php echo $this->config->public->grid_rows;?>" data-limit-navigation="5" data-filter="#search-filter">
			<thead>
			  <tr>
          <th data-sort-ignore="true" class="col4checkbox"><input id="check-all" type="checkbox" /></th>
		      <th data-type="numeric" data-ignore="true" data-hide="all">Id</th>
		      <th data-toggle="true">Name</th>
		      <th data-hide="phone" class="tctowrap">Value</th>
		      <th data-hide="phone" data-name="AutoLoad" class="tc2chars" title="Auto Load">AL</th>
		      <th data-hide="phone,tablet">Identity</th>
		      <th data-sort-ignore="true" data-hide="phone,tablet">Description</th>
		      <th data-sort-ignore="true" data-hide="xtablet,xphone" class="column-icon"></th>
		      <th data-sort-ignore="true" data-hide="xtablet,xphone" class="column-icon"></th>
			  </tr>
			</thead>
			<tbody>
			<?php foreach($data_options as $data_option) { ?>
				<tr data-id="<?php echo $data_option->option_id;?>">
					<td class="col4checkbox"><input class="check-rows" name="checked_id[]" type="checkbox" value="<?php echo $data_option->option_id;?>" /></td>
					<td><?php echo $data_option->option_id;?></td>
					<td><?php echo $data_option->option_name;?></td>
					<td>
						<?php 
							$safeText = htmlspecialchars($data_option->option_value);
							echo '<pre class="pre-scrollable"><code>';
							echo $safeText;
							echo '</code></pre>';
						?>
					</td>
					<td><?php echo strtoupper($data_option->option_autoload);?></td>
					<td><?php echo $data_option->option_identity;?></td>
					<td><?php echo $data_option->option_description;?></td>
					<td><button class="btnEdit btn btn-primary btn-xs" data-option_id="<?php echo $data_option->option_id;?>" title="Edit `<?php echo $data_option->option_name;?>`"><span class="glyphicon glyphicon-edit"></span></button></td>
					<td><button class="btnDelete btn btn-danger btn-xs" data-option_id="<?php echo $data_option->option_id;?>" title="Delete `<?php echo $data_option->option_name;?>`"><span class="glyphicon glyphicon-remove"></span></button></td>
				
				</tr>
			
			<?php } ?>
			</tbody>
      <!-- tfoot class="hide-if-no-paging">
	      <tr>
	      	<td></td>
		      <td colspan="4">
	          <ul class="pagination pull-right"></ul>
		      </td>
	      </tr>
      </tfoot -->
		
		
		
		</table>
	</div>
  <div class="hide-if-no-paging">
    <ul class="pagination pull-right"></ul>
	</div>

</div>

<div id="editOption" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Edit Option</h4>
      </div>
      <div class="modal-body">
				<form role="form">
					<input type="hidden" id="purpose" value="" />
					<input type="hidden" id="option_id" value="" />
				  <div class="form-group">
				    <label for="option_name">Option Name</label>
				    <input type="text" class="form-control" id="option_name" />
				  </div>
				  <div class="form-group">
				    <label for="option_value">Option Value</label>
				    <textarea id="option_value" class="form-control" rows="2" ></textarea>
				  </div>
				  <div class="checkbox">
				    <label>
				      <input type="checkbox" id="option_autoload" /> AutoLoad
				    </label>
				  </div>
					<div class="form-group">
						<label for="option_identity">Option Identity</label>
						<select class="form-control" id="option_identity" name="option_identity">
						<?php
							foreach($identities as $identity) {
								if ($identity=="-") {
									echo '<option class="disabled divider" disabled="disabled">';
									echo '</option>';
								} else {
									echo '<option value="' . $identity . '">';
									echo $identity;
									echo '</option>';
								}
						  }
					  ?>
						</select>
					</div>
				  <div class="form-group">
				    <label for="option_description">Description</label>
				    <input type="text" class="form-control" id="option_description" />
				  </div>
				</form>
				<div id="alertMsg" class="alert alert-success hide"></div>
      </div>
      <div class="modal-footer">
        <button type="button" id="btnSave" class="btn btn-primary">Save changes</button>
        <button type="button" id="btnClose" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div id="deleteOptions" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 id="myModalLabel">Delete Option(s)</h3>
			</div>
			<div class="modal-body">
				<form role="form">
					<input type="hidden" id="option_id" value="" />
				</form>
				<p>Are you sure you want to delete selected option(s)?</p>
			</div>
			<div id="alertMsg" class="alert alert-danger hide"></div>
			<div class="modal-footer">
				<button type="button" id="btnDeleteNow" class="btn btn-primary" class="btn btn-primary">Delete</button>
				<button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
			</div>
		</div>
	</div>
</div>